version: '3.8'

services:
  db:
    image: postgres
    volumes:
      - new_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    networks:
      - server-node-db
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - server-node-db
networks:
  server-node-db:
    driver: bridge

volumes:
  new_volume: